### ISSUE TITLE
Minor visual bugs

### ISSUE THREAD

**Issue by justingolden21** [tricinel/svelte-timezone-picker#18]
![image](https://user-images.githubusercontent.com/30274440/160296676-28eebc38-0d02-4cf4-8a53-d46f386cc1a2.png)

I noticed that when you type "pacific" that both timezones are highlighted. Also, there are two "x" buttons.

**Comment by tricinel** [comment]
Ah, interesting :) I might have Pacific under both Canada and US. Thanks for noticing!

**Comment by tricinel** [comment]
@justingolden21 unfortunately, I cannot reproduce that extra cross in there. Can you try this [codesandox demo](https://codesandbox.io/s/svelte-timezone-picker-demo-4ix87?file=/index.js) in the same browser you encounter the visual bug described and let me know if you still have it?

If you do, share your browser and version please :)

**Comment by justingolden21** [comment]
Sorry for the late reply

![image](https://user-images.githubusercontent.com/30274440/168495334-3abae4d0-4495-461d-a51e-c128580091d7.png)

Yeah I still encounter the same behavior. Thanks for looking into this.

**Comment by tricinel** [comment]
@justingolden21 what browser is that please?

**Comment by justingolden21** [comment]
Google chrome

**Comment by tricinel** [comment]
@justingolden21 that should fix it! Thanks for spotting it!

**Comment by justingolden21** [comment]
Awesome I'll check it out a bit later. Thanks for fixing it and for the quick work!

**Comment by tricinel** [comment]
Great! Closing now 👍
