### ISSUE TITLE
Uncaught ReferenceError: __USE_CUSTOM_EVENT__ is not defined

### ISSUE THREAD

**Issue by hcrohland** [tricinel/svelte-timezone-picker#2]
Using the picker I get that error.

Happens in my code and in the provided sandbox: https://codesandbox.io/s/svelte-timezone-picker-demo-4ix87

**Comment by tricinel** [comment]
Thanks for the feedback!

Yep, I haven't figured out yet how to fix it in the sandbox. __USE_CUSTOM_EVENT__ is inserted at build time by rollup.

Already working on a fix though.
